var
   base, altura,quantTinta: Inteiro
   area: Real
inicio
      Escreva ("Base da parede: ")
      Leia (base)
      Escreval
      Escreva ("Altura da parede: ")
      Leia (altura)
      Escreval
      area <- base * altura
      quantTinta <- area / 2
      Escreval
      Escreval ("- A área à ser pintada é de,",area," metros quadrados")
      Escreval ("- A quantidade gasta de tinta é de,",quantTinta," litros por metros quadrados")
fimalgoritmo
